sudo: false
language: c
cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/Martoon-00/range-tree/.stack-work"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc build --only-dependencies --jobs=4
script:
- # Tests
- stack --no-terminal build --test --jobs=4 --test-arguments --qc-max-success=10000
- # Benchmarks
- stack --no-terminal build --test --jobs=4 --flag range-tree:benchs
    --flag range-tree:-tests
